name = "WidthQualifiedFixedPointNumbers"
uuid = "29d17ff6-0dc8-409f-a66e-0ae4b5b27fc4"
version = "0.1.0"

[deps]
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"

[compat]
Aqua = "0.8"
FixedPointNumbers = "0.8"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
